### ISSUE TITLE
Correct spelling mistakes

### ISSUE THREAD

**Issue by ctranoris** [sensecitycode/Mobile-app#31]
λέξης "διάθεση" καθώς νομίζω ότι θέλει και δεύτερο τόνο όπως είναι αυτή την στιγμή διατυπωμένη η πρόταση.

Επίσης θεωρώ ότι κενό μεταξύ τελευταίας λέξεης και του colon χαλάει την "αισθητική".

**Comment by bakkostas** [comment]
Fixed!
